from enum import Enum


class WorkflowState(str, Enum):
    CREATED = "CREATED"
    DISCOVERING = "DISCOVERING"
    SCOUTING = "SCOUTING"
    SCORING = "SCORING"
    RESEARCHING = "RESEARCHING"
    ANALYZING = "ANALYZING"
    GENERATING_RESUME = "GENERATING_RESUME"
    ATS_REVIEW = "ATS_REVIEW"
    READY_TO_APPLY = "READY_TO_APPLY"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"